name: Deploy Straford to Azure

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Build project
        run: dotnet build StrafordWebApi/StrafordApi/StrafordApi.csproj -c Release

      - name: Publish project
        run: dotnet publish StrafordWebApi/StrafordApi/StrafordApi.csproj -c Release -o ./publish

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: Staford
          package: ./publish


